config/routes.rb
Rails.application.routes.draw do
# controller, #, then the action (action must have html page)
  root 'subs#index'

  # get 'sub#index', as: 'subs'
  # HTTP VERBS
    #get              index, show, new, edit, read
    #post             create
    #put              update
    #delete           destroy
  #this will make the routes for each of these verbs
resources :subs do
  resources :topics
end

resources :topics do
  resources :comments
end


  #can do resources :subs, only:[:index, :create] 
  # or resources :subs, except:[:delete]
  
  #to do topic routes, we need embedded routes (add "do")
      #in embedded routes, only go one deep

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :topic
end

app/models/sub.rb
class Sub < ApplicationRecord
  has_many :topics
  #assosciations
  #validations
  #logic
  # validate :name, presence: true
end

app/models/topic.rb
class Topic < ApplicationRecord
  belongs_to :sub
  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/subs_controller.rb
class SubsController < ApplicationController
#MVC
  #models -- logic on the tables 
  #views -- what the user sees and interacts with
  #controllers -- traffic directors

    #skinny controllers / fat  models
      #controllers should be simple, models should contain the logic
#Actions - what you can do in the app
  #always return one of three things. response(html, xml, json)
  #if it doesnt return a response, then redirect to an action that does

  #READ -- GET
    #index - show all records in the table

        # def index
        #   @model_name(s) = Model_name.all
        # end

    #show - show single record (needs an ID)

      # def show
      #   @model_name = Model_name.find(params[:id])
      # end 

    #edit - shows the updating form for a single record, (needs an ID)

      # def edit
      #   @model_name = Model_name.find(params[:id])
      # end

    #new - create form, creates a record in memory

      # def new
      #   @model_name = Model_name.new
      # end

  #CREATE -- POST
    #create - creates a new record in the database, from the new action

        # def create
        #   @model_name = Model_name.new(model_name_params)
        #   if @model_name.save
        #     do something or redirect somewhere
        #   else
        #     render :new
        #   end
        # end
        # .
        # .
        # . put this down low
        # private
        #   #this passes in certain actions
        #   def model_name_params
        #     params.require(:model_name).permit(:attr, :attr1, :attr2(no id/created@/updated@))
        #   end

  #UPDATE -- PUT
    #update - updates a single record in db, from the edit form

          # def update
          #   @model_name = Model_name.find(params[:id])
          #   if @model_name.update(model_name_params)
          #     do something or redirect somewhere
          #   else
          #     render :edit
          #   end
          # end

  #DESTROY -- DELETE
    #destroy - deletes the record from the db, needs ID

    # def destroy
    #   @model_name = Model_name.find(params[:id]).destroy

    #   redirect elsewhere
    # end

#Before action to keep things DRY
before_action :set_sub, only: [:show, :edit, :update, :destroy]



  def index
    @subs = Sub.all
  end

  def show
  end

  def new
    @sub = Sub.new
    render partial: 'form'
  end

  def create
    @sub = Sub.new(sub_params)
    if @sub.save
      redirect_to subs_path
    else
      render partial: "form"
    end
  end

  def edit
    render partial: 'form'
  end

  def update
    if @sub.update(sub_params)
      redirect_to subs_path
    else
      render partial: "form"
    end
  end

  def destroy
    @sub.destroy

    redirect_to subs_path
  end


  private

  def set_sub
    @sub = Sub.find(params[:id])
  end

  def sub_params
    params.require(:sub).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/subs_helper.rb
module SubsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsReddit</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/subs/_form.html.erb
<h1> <%= @sub.id ? 'Edit Sub' : 'New Sub' %> </h1>
</br>
<%= form_for @sub do |f| %>
  <%= f.label :name%>
  <%= f.text_field :name, required: true%>
  <%= f.submit %>
<% end %>

app/views/subs/edit.html.erb
<h1>Subs#edit</h1>
<p>Find me in app/views/subs/edit.html.erb</p>

app/views/subs/index.html.erb
<h1>All Subs</h1>
<%= link_to 'New Sub', new_sub_path%>
<ul>
  <% @subs.each do |sub|%>
    <li>
    <%= link_to sub.name, sub_path(sub) %>
    </li>
  <% end %>

</ul>

app/views/subs/new.html.erb
<h1>Subs#new</h1>
# <%= render 'sub/form' %>

app/views/subs/show.html.erb
<h1> <%=@sub.name%> </h1>
</br>

<%= link_to 'Edit Sub', edit_sub_path(@sub) %>
</br>

<%= link_to 'Delete Sub', @sub, method: :delete %>
</br>

<%= link_to 'View Topics', sub_topics_path(@sub) %>